### ISSUE TITLE
Enhancement Request: making initial mode customizable for ibus-mozc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#201]
```
Recently, IBus developers are changing the design of IBus; they try to let 
users use Eisu input mode of ibus-anthy or ibus-mozc instead of Japanese 
keyboard engine (xkb:jp::jpn).

A problem is ibus-mozc always starts with Hiragana mode although many users 
expect that it starts with Eisu mode.

Is is possible to make the initial mode of Mozc customizable?

My proposal is that users can choose one from:
- Always Eisu
- Always Hiragana
- Start with the previous mode (Mac OS X-like behavior)
The third option allows to save the last input mode and restore it at the next 
session. It is useful to use ibus-mozc in both the new way above and the old 
way with xkb:jp::jpn.

ibus-anthy will support this feature.
http://code.google.com/p/ibus/issues/detail?id=1662
```

Original issue reported on code.google.com by `f.takeya...@gmail.com` on 24 Oct 2013 at 3:51
- Blocked on: #287

**Comment by ckolivas** [comment]
Many of us depended on the default behaviour of starting in hiragana mode and now I'm unable to find a meaningful way to configure it to go to hiragana mode by default which means every time I switch input methods I also have to select hiragana from the system tray (on the few remaining desktop environments where it still works). How is this progress? How do we restore the original behaviour?

**Comment by yukawa** [comment]
Unfortunately there is no update since no one has volunteered to work on that. That's actually one of the the reasons why we decided to deprecate ibus-mozc (#287).  I with I could help, but I'm unable to spend as much time with ibus-mozc anymore as I'm also in charge of many projects such as Chromium and Android as well as other clients of Mozc such as Mozc for Android and Mozc for Windows.

If you wish to change the default behavior to the original one, I would do that if you could make a consensus among maintainers of ibus-mozc in major Linux distributions (Fedora, Ubuntu, Debian, openSuse, Arch, Gentoo, ...).  Please note that some people don't like the previous behavior as pointed out in the first post in this thread.
> A problem is ibus-mozc always starts with Hiragana mode although many users expect that it starts with Eisu mode.

Thank you for your understanding.

**Comment by ckolivas** [comment]
Thanks for responding. Ubuntu is defaulting to direct input which is the problem for me. As ibus-mozc is being deprecated I shall return to using ibu-santhy which defaults to hiragana, thank you.

**Comment by yukawa** [comment]
Just for your reference, Ubuntu 15.10 is supposed to start using [Fcitx](http://github.com/fcitx) rather than ibus as their default input method (input method framework), which is another reason for me to hesitate to spend my time to improve ibus-mozc. Probably [fcitx-mozc](https://github.com/fcitx/mozc) would be in far better situation than ibus-mozc in terms of maintenance resources.

See following pages about the direction of Ubuntu. 
- [language-selector 0.144 source package in Ubuntu](https://launchpad.net/ubuntu/+source/language-selector/0.144)
- [im-config 0.29-1ubuntu3 source package in Ubuntu](https://launchpad.net/ubuntu/+source/im-config/0.29-1ubuntu3)

**Comment by hanaokaiwa** [comment]
I am wondering why ibus-mozc behaves deferently as fcitx-mozc.
Which behavior should be right? How ibus-anthy and fcity-anthy behaves as default?
ibus-mozc's behavior now is just because somebody requests this. But I request for default method of HIRAGANA and  I think more people request the same than who requests for default of DIRECT.

**Comment by yukawa** [comment]
> ibus-mozc's behavior now is just because somebody requests this. But I request for default method of HIRAGANA and I think more people request the same than who requests for default of DIRECT.

I do understand you frustration, but the behavior change was actually based on recommendation by ibus core committer and ibus-mozc package maintainers of multiple Linux distributions (AFAIK package maintainers in openSuse and Ubuntu preferred this default behavior). It's not a random somebody at all. So if you really think we should change the behavior again, let me reiterate my previous comment.

> If you wish to change the default behavior to the original one, I would do that if you could make a consensus among ibus-mozc maintainers in major Linux distributions (Fedora, Ubuntu, Debian, openSuse, Arch, Gentoo, ...).

So please reach out ibus-mozc package maintainers of major Linux distributions to make a consensus to do that. If they (or most of them) agree to change the behavior, I'm happy to do that (if `ibus-mozc` is not removed from our repository yet. See #287 for details. Basically our plan is to discontinue the support of ibus some time soon)

**Comment by hanaokaiwa** [comment]
Thank you very much for your reply.
I just upgraded my Fedora and it took too much time for me to modify ibus-mozc's source code and rebuild the package.
Thank you very much for your explain. I know it is very difficult to change the behavior of ibus-mozc now. Thank you.

**Comment by Dreamsorcerer** [comment]
> Just for your reference, Ubuntu 15.10 is supposed to start using [Fcitx](https://github.com/fcitx) rather than ibus as their default input method (input method framework), which is another reason for me to hesitate to spend my time to improve ibus-mozc. Probably [fcitx-mozc](https://github.com/fcitx/mozc) would be in far better situation than ibus-mozc in terms of maintenance resources.

Did something change? I'm now on Ubuntu 20.04 and this is still an issue, it still seems to use ibus-mozc, and even if I install fcitx-mozc, it doesn't change anything.

**Comment by ftake** [comment]
Now we have a user config file for ibus-mozc. So I think we can resolve this issue.

**Comment by Dreamsorcerer** [comment]
Great, is there some documentation for this? Has it just been added, or is this already available (e.g. in Ubuntu 20.04)?

**Comment by ftake** [comment]
Sorry for my misleading comment. We still need some code to resolve this.

**Comment by Dreamsorcerer** [comment]
Ah, I see what you mean now. No problem.

**Comment by ftake** [comment]
I'e started PoC.
https://github.com/ftake/mozc/commits/feature/initial-composition-mode
This code is not tested at all for now.

You will be able to customize activated_on_launch and initial_composition_mode with ~/.mozc/ibus_config.textproto

**Comment by ftake** [comment]
It looks working as expected

For example, if you want to activate ibus-mozc with full Katakana mode, write following lines in that file.
By omitting `initial_composition_mode`, the initial mode becomes HIRAGANA.

```
activated_on_launch : true
initial_composition_mode : FULL_KATAKANA
```

**Comment by Nocifer** [comment]
Well, how very nice that after months and months of getting annoyed with this issue, I finally decide to come here and make a report about it, only to find that someone has just implemented a patch to solve it :)

The patch does work very nicely, and IMHO this should be the default behavior of Mozc. But, even though for my needs it's perfectly adequate as it stands, to really become complete it needs two more things: the first is of course to expose it in the GUI (instead of having to edit ibus_config.textproto) and the second is to make it so that whenever the user changes the input mode manually, Mozc will optionally remember this choice and set it as the new default for subsequent sessions.

**Comment by hiroyuki-komatsu** [comment]
Thank you very much Fuminobu for your suggestion and proof-of-concept.

As you suggested 467a91c enabled to configure the initial state on launch.
The implementation is different from your POC, but the concept is equivalent.

Default ~/.config/mozc/ibus_config.textproto
```
engines {
  name : "mozc-jp"
  longname : "Mozc"
  layout : "default"
  layout_variant : ""
  layout_option : ""
  rank : 80
}
active_on_launch: False
```

Sample configuration
```
engines {
  name : "mozc-jp"
  longname : "Mozc"
  layout : "ja"
  layout_variant : ""
  layout_option : ""
  rank : 80
}
active_on_launch: True
```

Sample configuration #2
```
engines {
  name : "mozc-jp"
  longname : "Mozc"
  layout : "ja"
  layout_variant : ""
  layout_option : ""
  rank : 80
}
engines {
  name : "mozc-us"
  longname : "Mozc US"
  layout : "us"
  layout_variant : ""
  layout_option : ""
  rank : 80
}
active_on_launch: True
```

You may need to run `ibus restart` after the modification.

**Comment by ftake** [comment]
Thank you.
I'm very happy for making this customizable because I suggested turning the default mode to IME off for IBus 1.5, 6 years ago.

**Comment by Orzelius** [comment]
Can I configure this on Windows (google Japanese input) somehow or I have to build and install Mozc on its own?
