### ISSUE TITLE
If you made a change to affect fcitx-mozc/uim-mozc,

### ISSUE THREAD

**Issue by heathross** [google/mozc#293]
If you made a change to affect fcitx-mozc/uim-mozc,
please tell it to fcitx-mozc/uim-mozc developers.

I did it twice.
https://code.google.com/p/fcitx/issues/detail?id=755
https://code.google.com/p/fcitx/issues/detail?id=747

You changed it on 31 May,
https://github.com/google/mozc/commit/dbe800583e5676896ce603494ef3b306f38f7b85
but no one reported it to fcitx/uim developers.

**Comment by yukawa** [comment]
Sorry, we don't have enough engineering resources to make sure that our changes do not break any downstream projects. Can you set an automated continuous integration mechanism so that we can catch this kind of breakage immediately after we make changes in master branch?  Are there any Docker images or Travis CI configurations to make sure our changes do not break {uim/fcitx}-mozc?

**Comment by yukawa** [comment]
> If you made a change to affect fcitx-mozc/uim-mozc,
> please tell it to fcitx-mozc/uim-mozc developers.

The real problem here is that this kind of breakage is really hard to predict. Basically it is almost impossible to avoid breakages in build and/or functionality, especially when a change affect multiple projects directly or indirectly. So what you did is indeed correct.  What we should do is to detect this kind of breakage as soon as possible and simply fix it.  I hope our commit log has sufficient information for that.

I would suggest you set up your own automated mechanism to make sure following things:
  * Every new commit to Mozc master branch can be merged into your project (fcitx-mozc, uim-mozc, your super cool Android IME based on Mozc, or whatever that depends on Mozc) without any conflicts.
  * You can build your project with such a new commit in Mozc master branch.
  * All unittests succeed.
Doing above tasks manually doesn't make sense and is not sustainable actually.
