### ISSUE TITLE
Settings dialog not scaled properly on HiDPI displays

### ISSUE THREAD

**Issue by Tilka** [google/mozc#326]
The Mozc settings dialog looks like this and is not resizable:

![screenshot from 2015-11-08 20-13-22](https://cloud.githubusercontent.com/assets/123798/11022060/9ad6adaa-8655-11e5-801a-d4202624cd78.png)

I'm using the mozc-ut package from the Arch User Repository (slightly patched to build 453df28947459f2730643fbeea665448d8d1d86e) with a 15.5" 3K display.

**Comment by yukawa** [comment]
Thank you for reporting this issue.  We are aware of this issue, and we plan to address this kind of issues as a part of our Qt 5 migration (#327).  For now I'm going to close this one since we don't plan to address this in our Qt 4 version of ```mozc_tool```.  Please subscribe #327 if you are interested in the progress on our Qt 5 migration.

Just FYI, this is not specific to Linux version.
- [Google Japanese Input Help Forum - WindowsのDPIスケーリング](https://productforums.google.com/forum/#!topic/ime-ja/Lws2xL9jV68)
- [Google Japanese Input Help Forum - Windowsのhigh DPIモードへの対応](https://productforums.google.com/forum/#!topic/ime-ja/O2u7DTyPzTw)

**Comment by yukawa** [comment]
Seems that Qt project plans to introduce [cross-platform HiDPI support](http://lists.qt-project.org/pipermail/development/2015-June/021631.html) in Qt 5.6, which is going to be shipped soon.
