### ISSUE TITLE
ITextStoreACP::GetACPFromPoint() is sometimes not called after ITextStoreACP::GetTextExt() returns TS_E_NOLAYOUT

### ISSUE THREAD

**Issue by masayuki-nakano** [google/mozc#339]
I'm not sure if this is a bug, though.

When I convert composition string on TSF-aware application (I tested with Firefox), ITextStoreACP::GetTextExt() is called 3 time. When I type a character and press spacebar, I see these calls during a document lock:

1. ITextStoreACP::GetTextExt(acpStart=0, acpEnd=1)
2. ITextStoreACP::GetTextExt(acpStart=1, acpEnd=1)
3. ITextStoreACP::GetTextExt(acpStart=0, acpEnd=1)

Only after 2nd call, mozc doesn't check if it returns TS_E_NOLAYOUT with a call of ITextStoreACP::GetACPFromPoint(). (This hack is necessary because TSF converts TS_E_NOLAYOUT to E_FAIL at calling ITextStoreACP::GetTextExt(), but not so at calling ITextStoreACP::GetACPFromPoint())

**Comment by yukawa** [comment]
Thank you for the report, I can reproduce the issue you reported in for following environment.
* Firefox 43.0.2
* Windows 10 (10586.36)
* Mozc-2.17.2262.100

That said, I don't think the 2nd call was made by Mozc. Thus I'd like to close this issue as I think you should report this issue to Microsoft rather than us.  Let me know if you disagree.

## Background
Here is [a detailed sequence graph](https://docs.google.com/spreadsheets/d/1nV5rthnZx3riONgY2VhffQBpYdaKvpkiXBhSG17OsNU/view#gid=0) I made. As for the 1st call of [ITextStoreACP::GetTextExt](https://msdn.microsoft.com/en-us/library/windows/desktop/ms538435.aspx) at line 38, yes I can confirm that it was from [```mozc::win32::tsf::TipRangeUtil::GetTextExt```](https://github.com/google/mozc/blob/cac146508d32fcce1ecfec8d038f63f588ed13c4/src/win32/tip/tip_range_util.cc#L226-L261), which internally calls [```ITfContextView::GetTextExt```](https://msdn.microsoft.com/en-us/library/windows/desktop/ms538782.aspx). However, the 2nd call at line 53 was not ours.  It was made by ```tiptsf.dll!CCorrectionIMX::_GenerateCaretEvents```, which is apparently developed by Microsoft.  I think this is something that should be fixed in TSF runtime.

Thanks,
