### ISSUE TITLE
ImmSetCandidateWindow() with CFS_EXCLUDE isn't supported on Win Vista and Win7

### ISSUE THREAD

**Issue by masayuki-nakano** [google/mozc#361]
As far as I know, Google Japanese Input is installed as IMM-IME. Actually, when I use it on Firefox which is TSF-aware, Google Japanese Input doesn't work with TSF APIs (e.g., ITextStoreACP).

Firefox uses CFS_EXCLUDE for specifying candidate window position in horizontal layout mode. However, this won't work will with Google Japanese Input on Win Vista and Win7. I know it shouldn't work on Win8 or later because Google Japanese Input is installed as TSF-TIP and CUAS doesn't support CFS_EXCLUDE when applications call ImmSetCandidateWindow().

You can test this with following steps (I tested with Google Japanese Input 2.17.2400.0):
1. Load https://bug1243268.bmoattachments.org/attachment.cgi?id=8713081 with Firefox on Win Vista or Win7
2. Type "わたしのなまえはなかのです"
3. Convert it until candidate window is shown

Firefox specifies CFS_EXCLUDE whose rect includes whole selected clause in the composition string. So, the selected clause shouldn't be overlapped with candidate window but Google Japanese Input show it under first character of the selected clause.

This bug is very annoying if the editor is vertical writing mode.

I cannot reproduce this bug with Google Japanese Input 1.13.1641 on WinXP.

**Comment by yukawa** [comment]
Environment
-------------------------
 - Mozc 2.17.2320.100 and prior (built for IMM32)
 - Firefox Nightly (32-bit) 48.0a1 (2016-03-12)
 - Windows 10 1511 (OS Build 10586.122)

How to setup the environment to reproduce
-------------------------
1. Build Mozc for Windows as explained in [How to build Mozc in Windows](https://github.com/google/mozc/blob/master/doc/build_mozc_in_windows.md) 
2. Install Mozc for Windows as IMM32 client as explained in [Register Mozc for IMM32 into 64-bit environment](https://github.com/google/mozc/blob/master/doc/build_mozc_in_windows.md#register-mozc-for-imm32-into-64-bit-environment)

Steps to reproduce
-------------------------
1. Load https://bug1243268.bmoattachments.org/attachment.cgi?id=8713081 with Firefox Nightly 48.0a1 (2016-03-12)
2. Type "わたしのなまえはなかのです"

Expected behavior
-------------------------
After the step 2, both suggestion window and conversion window should respect the rectangle specified by Firefox with ```CANDIDATEFORM::rcArea```.
![mozc_issue361_expected](https://cloud.githubusercontent.com/assets/5861397/13726922/2ea395d2-e891-11e5-9473-fd204a228f70.png)

Actual behavior
-------------------------
After the step 2, both suggestion window and conversion window do not respect the rectangle specified by Firefox with ```CANDIDATEFORM::rcArea```.
![mozc_issue361_actual](https://cloud.githubusercontent.com/assets/5861397/13726899/29aea98c-e890-11e5-8665-58052b0c6e09.png)
