### ISSUE TITLE
Is there a way to set hiragana as default?

### ISSUE THREAD

**Issue by GAumala** [google/mozc#381]
I'm using Mozc 2.17.2240.102 in Arch Linux with the GNOME desktop environment. Everytime I switch to Mozc it starts in input mode "Direct Input" which doesn't write any hiragana. I have to manually set input mode to hiragana to start writing every time. Is it possible to change the default input mode?

**Comment by yukawa** [comment]
> Is it possible to change the default input mode?

Technically, yes, it's possible.  You can do that by modifying the source code and rebuild the binaries by yourself.  All you need to do is to replace ```const bool kActivatedOnLaunch = false;``` with ```const bool kActivatedOnLaunch = true;``` in [src/unix/ibus/property_handler.cc](https://github.com/google/mozc/blob/096650398addf9548a49403e1658a21b6e55b4e4/src/unix/ibus/property_handler.cc#L78-L86) then rebuild the ibus-mozc binary.
```
// Some users expect that Mozc is turned off by default on IBus 1.5.0 and later.
// https://code.google.com/p/mozc/issues/detail?id=201
// On IBus 1.4.x, IBus expects that an IME should always be turned on and
// IME on/off keys are handled by IBus itself rather than each IME.
#if IBUS_CHECK_VERSION(1, 5, 0)
const bool kActivatedOnLaunch = false;
#else
const bool kActivatedOnLaunch = true;
#endif  // IBus>=1.5.0
```

More background can be found in #201.

**Comment by GAumala** [comment]
That worked for me! Thank you very much for your hard work.

**Comment by tvdstaaij** [comment]
I just created a [customizepkg](https://github.com/ava1ar/customizepkg) customization to install [mozc-ut](https://aur.archlinux.org/packages/mozc-ut/) (which provides the ibus version by default) with this source modification. See [this gist](https://gist.github.com/tvdstaaij/a25bb1bd132eebea9b4d04f06be802ee). Might be useful to other Arch Linux users who install mozc from the AUR.

**Comment by zignd** [comment]
Hi @hiroyuki-komatsu! Looking from commit history you seem to be the most active developer on the project. Could you add an UI control or a parameter that could be set somewhere to allow users to set this option?

**Comment by hiroyuki-komatsu** [comment]
Hi Igor,

The latest version has the parameter to use Hiragana as the default mode.

I added the document for the configurations.
https://github.com/google/mozc/blob/master/docs/configurations.md

**Comment by giner** [comment]
Ubuntu 22.04 is still using an older version of mozc. One of temporary workaround is rebuilding mozc https://gist.github.com/giner/77f5b0f7c14603ce5e78b6fcebf48162.

**Comment by foxy123** [comment]
> Ubuntu 22.04 is still using an older version of mozc. One of temporary workaround is rebuilding mozc https://gist.github.com/giner/77f5b0f7c14603ce5e78b6fcebf48162.

Does it still work? I've tried it on Ubuntu 22.10 and I cannot see any difference.

**Comment by hiroyuki-komatsu** [comment]
That feature is supported by 2.26.4317 or later.
Please make sure the version on Ubuntu 22.10.

https://github.com/google/mozc/blob/master/docs/configurations.md#activate-mozc-on-launch

**Comment by foxy123** [comment]
> That feature is supported by 2.26.4317 or later. Please make sure the version on Ubuntu 22.10.
> 
> https://github.com/google/mozc/blob/master/docs/configurations.md#activate-mozc-on-launch

Oh, thanks so much. Now I have figured out how to make it work!

**Comment by ca9071jp2** [comment]
same file on windows?

**Comment by Slider-Whistle** [comment]
Don't know how I'm just now catching up on this (Gentoo might have been real slow to update this package, or I had something misconfigured) or if there's anyone else this suddenly might be affecting, but this commit https://github.com/google/mozc/commit/467a91c5b237ef9f519075b42e7c4585281e168f#diff-7e1afc0e343ee4fe6266908ae286af72842fdc840973548b49983ef94ac959f1 back in 2021 appears to have removed the kActivatedOnLaunch for anybody who might still be confused on where it's gone.

Rather than patching the package, you should now follow the advice in https://github.com/google/mozc/issues/381#issuecomment-877558661.

Sorry to bother everyone who has this issue as a watched thread

**Comment by ryosuketc** [comment]
@hiroyuki-komatsu I enabled https://github.com/google/mozc/blob/master/docs/configurations.md#activate-mozc-on-launch, which actually worked.
But what I ideally want is keeping my default *input language* to English, and chnage only the default *input mode for Japanese* to Hiragana when I switch to Japanese input.
The current behaviour seems to change the default language to Japanese Hiragana, rather than English.

Is such configuration already available?

**Comment by Slider-Whistle** [comment]
Hey @ryosuketc, I think the config you're looking for should be under your choice of IME engine, rather than mozc itself. Given that this issue relates to ibus, what you're probably going to want to do is run "ibus-setup", navigate to the second tab "Input Method", and then verify an input method called "English - English (US)" (I'm assuming that's what you want) appears there.
If English is available there, and it's not being used by default, then there's probably some other software in your OS (like your desktop environment, or a job in your init system) modifying the default keyboard layout. On looking further into things, it looks like ibus itself doesn't have any method for setting a "default", it apparently just goes with whatever's already been set when it starts up?
Anyway, knowing what OS and Desktop Environment you're using would help me look into changing its settings, but for now running the commands `env|grep LANG` and `setxbkmap -print` would be a good start.

**Comment by ryosuketc** [comment]
Thanks @Slider-Whistle for the comment. I will test more tomorrow but for now the OS is Ubuntu 24.04 LTS.
If that matters my env for LANG is `LANG=en_US.UTF-8`.

My Settings > Keyboard > Input sources has two in order: English (US) and Japanese (Mozc) follows. When I set `active_on_launch: True `, it actually overrides the order and switches Japanese to the top with Hiragana selected.
Instead, what I really want is Mozc respects the system-level language order (English > Japanese) but only changes the default input mode for Mozc to Hiragana instead of "direct input".

**Comment by yukawa** [comment]
For further discussions let's start a new thread at https://github.com/google/mozc/discussions

**Comment by yukawa** [comment]
Seems that auto-reference doesn't work for locked issue so I'm manually cross-referencing to a discussion where this thread gets mentioned. 

* https://github.com/google/mozc/discussions/925
