### ISSUE TITLE
ImportError: gen_zip_code_seed.py

### ISSUE THREAD

**Issue by gary816** [google/mozc#391]
#### Mozc-2.18.2620.102+24.0.oss
```
$ cd mozc-2.18.2620.102/src/dictionary/
$ python2 gen_zip_code_seed.py --zip_code=KEN_ALL.CSV --jigyosyo=JIGYOSYO.CSV >> test
Traceback (most recent call last):
  File "gen_zip_code_seed.py", line 59, in <module>
    from dictionary import zip_code_util
ImportError: No module named dictionary
```

This will fix it.
```
sed -i "s/from dictionary import zip_code_util/import zip_code_util/g" gen_zip_code_seed.py
```

**Comment by yukawa** [comment]
Thank you for the report and sorry about the trouble. This is actually a known issue regarding how Mozc team open-sources code from internal repository to GitHub. In internal repository, we assume that `PYTHONPATH` always includes the top directory of Mozc's source directory. Although we can forget about this when building Mozc because `build_mozc.py` automatically does this \[1\] for you, we have to do that manually when we manually run our Python scripts from console.

Can you try the following command instead? 
```
cd mozc-2.18.2620.102/src
PYTHONPATH="${PYTHONPATH}:${PWD}" python gen_zip_code_seed.py --zip_code=KEN_ALL.CSV --jigyosyo=JIGYOSYO.CSV >> test
```
We will update the comment in [`src/data/dictionary_oss/README.txt`](https://github.com/google/mozc/blob/d87954bf3791fb871c6e16621077fb0b97cc10a5/src/data/dictionary_oss/README.txt) in a later commit to make it clear that we have to manually set `PYTHONPATH`.

\[1\]: [src/build_mozc.py] (https://github.com/google/mozc/blob/f76c304164e54414b5310010bc26e27b37764822/src/build_mozc.py#L850) automatically updates `PYTHONPATH` as follows:
```
  # Add the mozc root directory to PYTHONPATH.
  original_python_path = os.environ.get('PYTHONPATH', '')
  depot_path = MOZC_ROOT
  python_path = os.pathsep.join([original_python_path, depot_path])
  os.environ['PYTHONPATH'] = python_path
```
