### ISSUE TITLE
ibus-mozc doesn't work when switching from Russian layout

### ISSUE THREAD

**Issue by WGH-** [google/mozc#408]
I have three layouts in ibus: `['xkb:us::eng', 'mozc-jp', 'xkb:ru::rus']`.

mozc only works correctly when switching from English. If you switch from Russian layout to mozc, it will type Cyrillic letters instead of functioning properly.

```
% ibus version
IBus 1.5.14
```

It happens on at least mozc-2.16.2037.102 and mozc-2.20.2677.102.

**Comment by WGH-** [comment]
FWIW, anthy doesn't suffer from this.

**Comment by WGH-** [comment]
This is caused by layout option in `/usr/share/ibus/component/mozc.xml`. So basically if you change layout from `default` to `jp`, it works correctly. Anthy uses `jp` as well, which explains why Anthy doesn't have this issue.

```diff
diff --git a/component/mozc.xml b/-
index a7be498..0000000 100644
--- a/component/mozc.xml
+++ b/-
@@ -16,7 +16,7 @@
   <icon_prop_key>InputMode</icon_prop_key>
   <icon>/usr/share/ibus-mozc/product_icon.png</icon>
   <setup>/usr/lib64/mozc/mozc_tool --mode=config_dialog</setup>
-  <layout>default</layout>
+  <layout>jp</layout>
   <name>mozc-jp</name>
   <longname>Mozc</longname>
 </engine>
```

**Comment by WGH-** [comment]
Ping. Any reasons why `default` should be used instead of `jp`?

**Comment by WGH-** [comment]
Some related discussion can be found here: ibus/ibus#1943

**Comment by hiroyuki-komatsu** [comment]
Hi, sorry for too late reply,

The `default` basically  works well unless the user uses multiple keyboard layouts like this issue.
If we use `jp` here, people who use the `us` layout will have an inconsistent layout problem for example.

As you mentioned, you can specify the keyboard layout by modifying `mozc.xml` if you have the root permission.

Since 9ba59b64d53365c1fe93c1c245b4ec3e35bdadf0, the setting is moved to your home directory.
So you do not need the root permission.
