### ISSUE TITLE
Modifier insensitive conversion (off) does not work for the last kana correctly.

### ISSUE THREAD

**Issue by justoneplanet** [google/mozc#415]
### Devices

- Nexus 5x

### What version of the product are you using? On what operating system?

Android
7.1.1

mozc
2.16.2038.103

Google Japanese Input
2.20.2802.3.148308588-arm64-v8a

### What steps will reproduce the problem?

Type "くしは", when Modifier insensitive conversion is off.

### What is the expected output?

The candidate "串パ" will not be suggested.

### What do you see instead?

But we will see the candidate "串パ".

### Please provide any additional information below.

The following behavior we can convert on the app will be right.

- ON : はーてい => パーティ
- OFF : はーてい => x

On the other hand,

- ON : くしぱ => 串パ
- OFF : くしは => 串パ

This will be unexpected. In addition, if we type a kana after it,

- ON: くしぱに => 串パに
- OFF: くしはに => x

 This behavior is changed unexpectedly.

**Comment by hiroyuki-komatsu** [comment]
This behavior comes from the expansion of composition rules (known as the romaji table). It is an intended behavior.

For example, in romaji input, "あｋ" is expanded to "あ[ｋかきくけこっ]" because "ｋ" can be changed either of "ｋかきくけこっ".
Like this, "は" can be changed to either of "はばぱ", then candidate words come form all possible combinations. 


If we remove this feature, "串パ" is blinked while the user is typing. We'd like to avoid this situation. 
Thank you,
