### ISSUE TITLE
Follow the XDG Base Directory specification

### ISSUE THREAD

**Issue by GovanifY** [google/mozc#474]
Hello,
on Linux the user profile directory is hardcoded to ~/.mozc in the source code, as seen there: https://github.com/google/mozc/blob/master/src/base/system_util.cc#L247 , which is against the XDG Base Directory specification ( https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ). This specification is now used by default for any recent-ish linux applications including google-backed ones such as chromium.

https://github.com/google/mozc/issues/470 could solve this issue by adding environmental variables, or we could switch to an XDG-compliant path by default on Linux, and revert to the old one if  found. Any thoughts?

**Comment by hiroyuki-komatsu** [comment]
Hi, it sounds good. Thank you for the feedback.

The commit 91cc1e19ef34aeb12888b697fefa52907f1a834d contains the support for $XDG_CONFIG_HOME.

Since the above commit, Mozc uses and creates the configuration directory as follows:
1. If $HOME/.mozc already exists → $HOME/.mozc
2. If $XDG_CONFIG_HOME is defined →  $XDG_CONFIG_HOME/mozc
3. Otherwise → $HOME/.config/mozc  as the default value of $XDG_CONFIG_HOME
