### ISSUE TITLE
Please clarify goals of the ongoing development

### ISSUE THREAD

**Issue by akirak** [google/mozc#484]
Hello, I was using mozc inside Emacs. I used `mozc_emacs_helper` produced by a custom build instruction for [Nix](https://github.com/NixOS/nixpkgs/) in my configuration repository.

It's generally welcome to get updates on software I'm using, but recent changes in this repository broke my build, which forced me to stop writing Japanese inside Emacs. I don't know when it's going to end (i.e. become stable in terms of how to build).

So I would like to ask: What is your plan/policy for development of mozc? Why are you making these changes, and when is it going to end? If I understand what is going on here, I may be able to update the packages in Nixpkgs as needed.

**Comment by omasanori** [comment]
I would support @akirak's point. The "upstream" referred in commit messages is probably Google's internal tree, but then what will we see in the (foreseeable) future?

**Comment by hiroyuki-komatsu** [comment]
Hello, almost all the recent changes were code refactoring and updates of build systems, as the commit messages describe. We would like to communicate what we have done rather than what we will do. If you have questions about specific changes, please let us know. We would describe the background of the change.

When you find a build break in your environment, please make sure it also happens in our [Docker build environment](https://github.com/google/mozc/blob/master/docs/build_mozc_in_docker.md).

If the Docker build works well, that issue comes from the gap of the build environments. In this case, please update your build environment to be align with the Docker environment, or please talk with the contacts of your environment.

Thank you,

**Comment by akirak** [comment]
Thanks for the explanation. I am slightly frustrated with spontaneous changes in the build instruction and the rolling release style, but I will deal with it by pinning my source repository to a specific commit, as suggested in the README:

> If you are interested in packaging Mozc source code, or developing your own products based on Mozc, feel free to pick up any version.

**Comment by Arfrever** [comment]
@hiroyuki-komatsu: Could you explain goal for recent removal of handwriting recognition support? (Directories `src/gui/character_pad` and `src/handwriting` in commit a1dcadabd3a1c604e8beff1e45830c1d9adfce84.)

Also why `REVISION=102` was changed to `REVISION = 100` in `src/data/version/mozc_version_template.bzl` in commit a1dcadabd3a1c604e8beff1e45830c1d9adfce84?
It does not match documented practice in https://github.com/google/mozc/blob/master/docs/about_branding.md.
According to `Version String` row, value `100` is for `Google Japanese Input Development Version (Windows)`, while `102` is for `Mozc`.

**Comment by hiroyuki-komatsu** [comment]
Hi Arfrever,

Handwriting: Because Google Japanese Input removed handwriting and character pad from the internal repository, the update by https://github.com/google/mozc/commit/a1dcadabd3a1c604e8beff1e45830c1d9adfce84 reflected that change.

Revision: The Linux version keeps 102. The build scripts read `mozc_version_template.bzl` and modify the revision to the target platform (e.g. 100 → 102 for Linux).
https://github.com/google/mozc/blob/master/src/build_tools/mozc_version.py#L103

Thanks,

**Comment by js290** [comment]
> Hi Arfrever,
> 
> Handwriting: Because Google Japanese Input removed handwriting and character pad from the internal repository, the update by [a1dcada](https://github.com/google/mozc/commit/a1dcadabd3a1c604e8beff1e45830c1d9adfce84) reflected that change.
> 

Could the handwriting portion be forked off or is it only old people that use handwriting input?
