### ISSUE TITLE
Support for system protobuf missing in Bazel build system

### ISSUE THREAD

**Issue by Arfrever** [google/mozc#509]
GYP build system supports `use_libprotobuf` option to enable linking with protobuf library (`-lprotobuf` passed to linker):
https://github.com/google/mozc/blob/492e6227de3adec93c1f294b6c68a42b85b4e7db/src/gyp/defines.gypi#L66
https://github.com/google/mozc/blob/0e5ac41427c835852797d350e0e0db4061c79186/src/protobuf/protobuf.gyp#L154-L160

Bazel build system appears to be missing equivalent option.

**Comment by hiroyuki-komatsu** [comment]
Hi Arfever,

We recommend to use protobuf with static link, so supporting dynamic link is not our focus.

On the other hand, we understand there are some preferences for dynamic link.
If you provide instructions or proof-of-concept to use protobuf with dynamic link,
we try to support dynamic link or tweak our code to easily apply patches for dynamic link.

I also try to make a time to check a way for dynamic linked protobuf,
but please understand my personal priority for it is not high.

**Comment by Tosainu** [comment]
I +1 for this.

The reason is that IME which is using the statically-linked protobuf (might) crashes the application which is using the system-installed and dynamically-linked protobuf. I'm not too sure why, but there are some similar issue reports (e.g. https://github.com/tensorflow/tensorflow/issues/16104) and they said that it is the symbol conflicts.

**Comment by hiroyuki-komatsu** [comment]
Hi Kenta,

That is actually one of reasons we prefer static links. If I understand correctly, that crash issue happens when we use mixtures of static links and dynamic links. That said, my understanding would be wrong. If there are actual crash cases caused by static links, please let us know.


Because supporting dynamic link is not our focus, we hope someone provides instructions or proof-of-concept to use protobuf with dynamic link. Then we try to support dynamic link or tweak our code to easily apply patches for dynamic link.

Thank you,

**Comment by yukawa** [comment]
Thank you for the feedback.

I'm going to close this as not planned, but before doing so I'm trying to summarize the situation a bit.

Let's start from understanding where we are. Now that protobuf depends on abseil, and Mozc also depends on both protobuf and abseil, there is indeed a "diamond dependency problem".

https://abseil.io/resources/swe-book/html/ch21.html
> The diamond dependency problem, and  other forms of conflicting requirements, require at least three layers of dependency, as demonstrated in [Figure 21-1](https://abseil.io/resources/swe-book/html/ch21.html#the_diamond_dependency_problem).
>
> ![The diamond dependency problem](https://abseil.io/resources/swe-book/html/images/seag_2101.png)
> Figure 21-1. _The diamond dependency problem_

https://abseil.io/about/philosophy#we-recommend-that-you-choose-to-live-at-head
> We believe that the current paradigm for software is inherently unsustainable: dependency management is brutally complex. Unsolvable “diamond dependency” issues are common — the only ways to avoid these are to never change, or to ensure that there aren’t multiple versions. We prefer the latter, so we will do what we can to get you to live at head along with us — if everything is built from source at head, there can be no more diamond dependencies, branch conflicts, and complicated discussions about merge policy. All of that time spent could be spent on more useful things, like actually writing code and solving problems for users. Join with Abseil, and stop paying the content-management tax!

Within Google, we are actually living at head. One of build configurations the Mozc team internally maintains inside Google indeed uses both the head version of protobuf and the head version of abseil. At the same time, for OSS Mozc, we pin both protobuf version and abseil version to avoid the above diamond dependency (c.f. https://github.com/google/mozc/issues/742#issuecomment-1545926484 ). Supporting these two pairs of versions is already a headache, but the Mozc team is OK about it. This is why the Mozc team deals with the above "diamond dependency problem".

On the other hand, Linux distributors tend to tackle this "diamond dependency problem" with an assumption that an upstream software could be compatible with different versions of dependent libraries, then unbundle all the C++ libraries into system-installed shared libraries so that all the application dynamically links to the same versions of the C++ libraries.

In other words, the Mozc team and (most of) Linux distributors are tacking the same "diamond dependency problem" in different approaches. I do understand that system-installed shared libraries can receive security fixes more easily, but Google has been shipping Google Japanese Input to Windows and macOS and Gboard for Android with statically linking abseil and protobuf for more than 10 years. The Mozc team has been satisfied with this approach.

I have also worked in the Android OS team and I'm pretty convinced that having a better sandbox technology and defining stable APIs are much more scalable in distributed software development ecosystem. As for Mozc for Linux, I think Flatpak and/or Snap would be better choice than each packager's having to package Mozc separately. Technically it should be doable by writing some shim between IBus engine process and Mozc server running in a sandbox. Such a shim doesn't exist right now, but I'm happy to discuss if there is anyone interested in.

Best,
