### ISSUE TITLE
Impossible to enter one single character in some Chromium text boxes

### ISSUE THREAD

**Issue by montanpi** [google/mozc#519]
Chromium: Version 92.0.4515.159 (Official Build) Arch Linux (64-bit)
fcitx version: 4.2.9.7
fcitx-mozc version: 2.26.4360.102.gca82d39-1

Cannot enter one single character in some Chromium text boxes. If entering one single character when the IME is active, Enter key is sent instead; this causes for example sending messages/forms/reloading websites involuntarily.
Only happens in Chromium. No problems with other browser or other applications.

[Video demonstration](https://youtu.be/JKzsOja2YNY)

**Comment by hiroyuki-komatsu** [comment]
Hi montanpi,

Thank you for your report with the video. It's helpful to understand the problem.

Does this problem happen with other IMF (e.g. fcitx5, Ibus, etc.) instead of fcitx?

If this problem happens only on fcitx and Chromium, this is a problem of fcitx or Chromium.
In this case, the problem is outside of this project.

**Comment by montanpi** [comment]
Hello Hiroyuki,
I was able to solve by replacing fcitx with fcitx5 and fcitx-mozc with fcitx5-mozc.
Thanks for pointing me in the right direction.
