### ISSUE TITLE
Qt candidate window: window size is still too small

### ISSUE THREAD

**Issue by ftake** [google/mozc#547]
The Qt candidate window of 2.26.4632 is still too small and all the its contents are not shown. Please see the screen shot attached.
Physical DPI of the display might be related to this problem.

Qt version: 5.15.2
Desktop: Xfce (also confirmed with KDE Plasma)
![Screenshot_opensusetumbleweed_2022-02-13_00:26:49](https://user-images.githubusercontent.com/160235/153717391-73afbb08-a986-417d-a3bc-bca8ac4ef423.png)

**Comment by hiroyuki-komatsu** [comment]
Hi Fuminobu,

Thank you for the report with the screenshot. It's helpful for us.

The margins of the low are different from our expectations.
![image](https://user-images.githubusercontent.com/11634377/153744020-b8b85eb2-ef1b-411c-8d63-e76e04a98ccc.png)

* Would you share your display settings?
* If you keep using the candidate window, is the margin changed to the expected size?

Because I cannot reproduce this issue on my environment (Debian testing, Qt 5.15.2+dfsg-14), I need helps to identify the problem.

Thank you,

**Comment by ftake** [comment]
Hi, here is additional information

* HW: Virt Manager (libvirt graphics + Spice)
* OS: openSUSE Tumbleweed
* Desktop environment: Xfce
  * Font DPI: 96
  * QT_AUTO_SCREEN_SCALE_FACTOR, QT_SCREEN_SCALE_FACTORS not set
* Virtual display
  * I'm not sure if there are some mechanisms to pass host's physical display metrics (using 27 inch 4K and 12 inch Full HD display)
 
```
> xrandr
Screen 0: minimum 320 x 200, current 1024 x 768, maximum 8192 x 8192
Virtual-1 connected primary 1024x768+0+0 (normal left inverted right x axis y axis) 370mm x 267mm
   1457x1055     75.00 +
   5120x2160     50.00  
   4096x2160     50.00  
   3840x2160     50.00  
   1920x1440     60.00  
   2560x1080     50.00  
   1856x1392     60.00  
   1792x1344     60.00  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    50.00  
   1600x1200     60.00  
   1680x1050     59.95  
   1400x1050     59.98  
   1280x1024     60.02  
   1440x900      59.89  
   1280x960      60.00  
   1360x768      60.02  
   1280x768      59.87  
   1024x768      60.00* 
   800x600       60.32  
   640x480       60.00    59.94  
```

One interesting fact is that this problem does not reproduce under icewm. So I'm wondering there are some padding from window managers.

**Comment by hiroyuki-komatsu** [comment]
I performed the whole refactoring to the Qt candidate window.
It has replaced Mozc's thread and mutex in the implementation with Qt's ones.

This issue doesn't happen my environment.
Would you confirm if the build 4656 works or not?

**Comment by ftake** [comment]
Unfortunately, 4656 does not resolve this problem.

According to my quick survey writing a simple Qt application, it seems that there is some minimum column-width and thus `setColumnWidth()` does not always set to the specified width.

One idea to resolve this problem is getting the actual width of column after calling `setColumnWidth()`. However, I think the minimum width is a bit wide for the shortcut column so I'm wondering if there's a way to adjust the min-width.

**Comment by ftake** [comment]
The following code seems to reduce the minimum width of colomun.

```C++
auto header = candidates_->horizontalHeader();
header->setMinimumSectionSize(1);
```

**Comment by hiroyuki-komatsu** [comment]
Thank you for the investigation.
I am going to make a change to call `setMinimumSectionSize`.

**Comment by hiroyuki-komatsu** [comment]
81108defe472953a7fc8df7444022f21d83e22a6 added a change to call `setMinimumSectionSize`.

Would you try the build 4660?

**Comment by hiroyuki-komatsu** [comment]
I'm glad to hear that the issue is fixed.

The padding in your first comment is wider than our expectation, and the padding in your last comment is our expectation.
We will modify the padding based on the font size, if the current paddings don't work on some environments.
Please feel free to file another issue for this topic as a reminder.

Thank you again for you reports and investigations.
