### ISSUE TITLE
The undo shortcut not working

### ISSUE THREAD

**Issue by shungo27** [google/mozc#556]
The undo shortcut not working.

```
Precomposition Ctrl Backspace Undo
```

Raspberry Pi OS Lite 64bit bullseye
Gnome 3.38.6
ibus-mozc 2.26.4220.102

**Comment by hiroyuki-komatsu** [comment]
Hi shungo27, thanks for the report.

Because the host applications also need to support the reconvert / undo features, those shortcuts may look like not working with those unsupported applications.

* Would you share the applications you tried?
* Would you check whether other IMEs (e.g. Anthy) support reconvert / undo features with those applications?

Thank you,

**Comment by hiroyuki-komatsu** [comment]
I checked the Undo feature of the latest version (2.26.4695) with the following apps on Debian.

* Gedit (40.1): works well
* Firefox (91.7.0esr): works well
* Chrome (100): partially works. fails to delete the commited word.

So I think Mozc works as expected, but some host applications (and/or IBus) do not support functionalities for Undo.
Mozc uses [`ibus_engine_delete_surrounding_text`](https://github.com/google/mozc/blob/master/src/unix/ibus/mozc_engine.cc#L501),
I guess applications on your environment do not support this feature yet.

Because this is out of cotrol for this project, I will close this issue.
Thank you,
