### ISSUE TITLE
ゲームで正常に動作しない

### ISSUE THREAD

**Issue by CRC32EX** [google/mozc#739]
**Description**
ゲームで正常に動作しません。
正常に動作しないとは以下のような意味です。
- Enterキーを押しても確定されない
- Backspaceキーを押しても変換候補が消えない

ゲームの名前は[アラド戦記](https://arad.nexon.co.jp/)です。
Microsoft IMEは正常に動作しますが[こちら](https://arad.nexon.co.jp/news/notice_view.aspx?no=11589)の設定を事前に行う必要があります

**Steps to reproduce**
1. ゲームを起動する
2. Enterキーを押してチャットを表示させる
![image](https://user-images.githubusercontent.com/25629617/236681490-9c220bf7-ec64-4c5c-a051-2879f269727d.png)

3. 「あ」を入力して変換する（スペースキーを押す）
![image](https://user-images.githubusercontent.com/25629617/236681517-0bc44d19-f007-4782-a487-5195bd573919.png)

**Expected behavior**
Enterキーを押すと変換候補が消える
![image](https://user-images.githubusercontent.com/25629617/236681636-be7e6a75-6f3b-4113-a5f8-30325f5d00de.png)

**Actual behavior**
Enterキーを押しても変換候補が消えない
![image](https://user-images.githubusercontent.com/25629617/236681658-7f96632a-5495-48ca-b5aa-0ac82a4b321a.png)

**Version or commit-id**
Mozc-2.28.5085.100+24.11.oss

**Environment**
 - OS: Windows 11 21H2

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + no
 - What applications this issue happens on (e.g. Chromium, gedit).
   + [アラド戦記](https://arad.nexon.co.jp/)
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + Google Chrome
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + no-investigation

**Additional context**
- Windows 11のみで発生する問題です。Windows10では発生しません。
- 「GoogleJapaneseInput-2.28.4650.0+24.10.9」でも同様の問題が発生します

**Comment by hiroyuki-komatsu** [comment]
Hi CRC32EX,

Thank you for your report with screenshots. It's helpful for us.

Looking at the behaviors and referring the official article by Microsoft, we think it is an issue of the application because the application uses their custom UI for IME. Or, it is possibly an issue of Windows 11.
https://jpwinsup.github.io/blog/2021/10/03/UserInterfaceAndApps/LanguageSupport_IME/previous_ime/

Thus, unfortunately, there are probably nothing we can do.
Since our code is publicly available, we hope it would be helpful for the application developers for their debugging.

Thank you,
