### ISSUE TITLE
Candidate window doesn't follow QT theme on Linux

### ISSUE THREAD

**Issue by BrianAllred** [google/mozc#792]
## Description
Candidate window doesn't follow the specified QT theme on Linux, which can make the candidates difficult to read and also cause eye strain (if it defaults to a bright color like white).

## Steps to reproduce
1. Set environment variable `QT_QPA_PLATFORMTHEME` to a dark theme.
2. Type using mozc so that the candidate window appears.

## Expected behavior
The candidate window appears using the correct theme.

## Actual behavior
The candidate window appears using an incorrect theme

## Screenshots
Incorrect theming:
![image](https://github.com/google/mozc/assets/5847511/a0738e83-089d-4ff1-be79-5d12cb4fc620)

For example, this is what anthy looks like:
![image](https://github.com/google/mozc/assets/5847511/db364060-970a-4788-bcfa-340af0ef3b58)

## Version or commit-id
mozc-2.29.5111.102-1.2

## Environment
 - OS: openSUSE Tumbleweed using latest Gnome Wayland
 - IMF: ibus
 - Related Applications: all

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + no
 - What applications this issue happens on (e.g. Chromium, gedit).
   + all
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + N/A
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + N/A

**Comment by yukawa** [comment]
Thank you for he report. Supporting dark theme has been our to-do list for long time.

For your case, you can uninstall `ibus-mozc-candidate-window` package from our environment to use IBus' default candidate window, which is what Anthy is using in your screenshot.

There following document also describes how to use IBus' default candidate window rather than Mozc's one.
https://github.com/google/mozc/blob/master/docs/configurations.md#use-the-default-ibus-candidate-window

As for our long term plan, I guess we may want to rely on [the corresponding settings in XDG Desktop Portal](https://github.com/flatpak/xdg-desktop-portal/issues/629) rather than relying on `QT_QPA_PLATFORMTHEME`, which cannot handle dynamic theme update. Here are several examples in other projects.

 * [GNOME](https://blogs.gnome.org/alicem/2021/10/04/dark-style-preference/)
 * [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=998903)
 * [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1734934)

I'm going to convert this to discussion as it's a bit unlikely to just use `QT_QPA_PLATFORMTHEME` anyway.
